apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-job
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: bike-market-backend:latest
          imagePullPolicy: Never
          command: ["python", "-m", "database.init_db_pg"]
          envFrom:
            - configMapRef:
                name: bike-market-config
      restartPolicy: Never